import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

export default function Home(props) {
  const employeees = props.employees;
  let i = 1;
  return (
    <>
      <Head>
        <title>Employee Lists</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.card}>
          <div className="mb-4 float-end">
            <Link className={styles.addEmploye__button} href="/addemployee">Add Employee</Link>
          </div>
          <table className={styles.table}>
            <thead className={styles.thead}>
              <tr>
                <th>Sl.</th>
                <th>Name</th>
                <th>Designation</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody className={styles.tbody}>
            {employeees.map(employee =>
              <tr>
                <td>{i++}</td>
                <td>{employee.name}</td>
                <td>{employee.designation}</td>
                <td>{employee.email}</td>
                <td>{employee.contact}</td>
                <td>
                  <Link href={`edit/${employee.id}`}>Edit</Link>&nbsp;/&nbsp;
                  <Link href="#">Delete</Link>
                </td>
              </tr>)}
            </tbody>


          </table>
        </div>
      </main>
    </>
  )
}

import path from 'path';
import { promises as fs } from 'fs';

export async function getStaticProps() {

  const readPath = path.join(process.cwd(), 'data');
  const getData = await fs.readFile(readPath+'/data.json','utf8');
  const employeeData = JSON.parse(getData);

  return {
    props: employeeData
  }
}
